#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        6
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Yad state=floating

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit system-wide privileges control
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
feh --bg-fill --randomize Pictures/wallpapers/* &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Cursor
xsetroot -cursor_name left_ptr &

# Network Applet
nm-applet --indicator &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
